### ISSUE TITLE
Detalle de Planes

### ISSUE THREAD

**Issue by TuOdoo** [RafaelAngelRamirez/barriotec#2]
En el detalle del departamento o producto, en los planes, desplegar como detalle dentro de cada tabla la descripción que se encuentra en el back en los planes (booking/ config / plans / description)

**Comment by RafaelAngelRamirez** [comment]
Propuesta de registro:
![image](https://user-images.githubusercontent.com/27775245/143691782-1fc0fed5-1a12-4d78-8794-04c65bb51c57.png)

**Comment by RafaelAngelRamirez** [comment]
Resultado final
![image](https://user-images.githubusercontent.com/27775245/143719868-687dc732-8301-465a-92c3-3eab1cf36908.png)
