### ISSUE TITLE
Descripción planes

### ISSUE THREAD

**Issue by TuOdoo** [RafaelAngelRamirez/barriotec#5]
Revisar las descripciones de los planes en el preview de los items

**Comment by RafaelAngelRamirez** [comment]
@TuOdoo

El formato que se le da en la descripción se refleja en el contenido (texto) consultado a la BD. 
![image](https://user-images.githubusercontent.com/27775245/143776781-376f7642-292d-4b13-bdc4-aa44db6b4a31.png)


El problema viene de cambiar el tipo de fuente. Si se pone solo en negrita, el formato se refleja en los depas. 
![image](https://user-images.githubusercontent.com/27775245/143776973-1b59a9c0-d408-4554-ae19-aad21eb50dd2.png)


![image](https://user-images.githubusercontent.com/27775245/143777076-fff9baa5-31dc-4421-b0d8-81db55877d25.png)


La solución es: 

1. Seleccionar todo el texto. 
2. Eliminar el formato. 
3. Seleccionar el texto a poner en negritas. 
4. Solo dar formato en negritas. 

![image](https://user-images.githubusercontent.com/27775245/143777213-b3d36c6a-069d-48e5-9ad9-193667ad38b1.png)

Las comas al final generan un espacio en blanco. Hay que retirarlas.
![image](https://user-images.githubusercontent.com/27775245/143777763-007e6490-b98f-4ad3-a284-2530af4692e5.png)
